name: Static analysis

on:
  push:
    branches:
      - main
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update
          --no-ansi
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist

      - name: PHPStan
        run: vendor/bin/phpstan
          analyse
          --error-format=github
