name: Test

on:
  push:
    branches:
      - master
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - 'high'
          - 'low'
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          ini-values: zend.assertions=1, assert.exception=1
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-${{ matrix.dep-version }}-php-

      - name: Install dependencies
        env:
          DEPENDENCIES: ${{ matrix.dependencies }}
          IGNORE_PLATFORM_REQS: ${{ matrix.php == '8.0' }}
        run: composer update
          --no-ansi
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
          $([ $IGNORE_PLATFORM_REQS = "true" ] && echo -n '--ignore-platform-reqs')
          $([ $DEPENDENCIES = "low" ] && echo -n '--prefer-lowest')
          --optimize-autoloader

      - name: PHPUnit
        run: vendor/bin/phpunit
          --coverage-clover coverage.xml

      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)
