name: Composer validate

on:
  push:
    branches:
      - main
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Run validate
        run: composer validate
